name: moviez_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^8.2.0
  json_annotation: ^4.8.1
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  hive_ce_flutter: ^2.3.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  pretty_dio_logger: ^1.4.0
  go_router: ^16.2.1
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  skeletonizer: ^2.1.0
  app_links: ^6.4.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  freezed: ^3.2.0
  hive_ce_generator: ^1.9.2
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env